import 'package:riverpod_annotation/riverpod_annotation.dart';

import '../../../core/providers/supabase_provider.dart';
import '../../auth/presentation/auth_provider.dart';
import '../data/meal_plan_repository.dart';
import '../data/meal_plan_repository_impl.dart';
import '../data/shopping_repository.dart';
import '../data/shopping_repository_impl.dart';
import '../domain/meal_plan.dart';
import '../domain/shopping_cycle.dart';
import '../domain/shopping_item.dart';

part 'meal_provider.g.dart';

/// Provider for the MealPlanRepository instance.
@riverpod
MealPlanRepository mealPlanRepository(MealPlanRepositoryRef ref) {
  final supabase = ref.watch(supabaseProvider);
  final profileAsync = ref.watch(currentProfileProvider);

  // Get household ID from profile
  String getHouseholdId() {
    if (profileAsync.hasValue) {
      return profileAsync.value?.householdId ?? '';
    }
    return '';
  }

  return MealPlanRepositoryImpl(supabase, getHouseholdId: getHouseholdId);
}

/// Provider for the ShoppingRepository instance.
@riverpod
ShoppingRepository shoppingRepository(ShoppingRepositoryRef ref) {
  final supabase = ref.watch(supabaseProvider);
  final profileAsync = ref.watch(currentProfileProvider);

  // Get household ID from profile
  String getHouseholdId() {
    if (profileAsync.hasValue) {
      return profileAsync.value?.householdId ?? '';
    }
    return '';
  }

  return ShoppingRepositoryImpl(supabase, getHouseholdId: getHouseholdId);
}

/// StreamProvider for today's meals.
@riverpod
Stream<List<MealPlan>> todayMealsProvider(TodayMealsProviderRef ref) {
  print('[todayMealsProvider] Fetching today\'s meals...');
  final mealRepo = ref.watch(mealPlanRepositoryProvider);
  final today = DateTime.now();
  return mealRepo.watchMealsForDate(today).map((meals) {
    print('[todayMealsProvider] ✅ Received ${meals.length} meals for today');
    return meals;
  });
}

/// StreamProvider for meals in a date range (e.g., for calendar view).
@riverpod
Stream<List<MealPlan>> allMealsProvider(AllMealsProviderRef ref) {
  print('[allMealsProvider] Fetching all meals...');
  final mealRepo = ref.watch(mealPlanRepositoryProvider);
  return mealRepo.watchAllMeals().map((meals) {
    print('[allMealsProvider] ✅ Received ${meals.length} total meals');
    return meals;
  });
}

/// StreamProvider for shopping list items.
@riverpod
Stream<List<ShoppingItem>> shoppingListProvider(ShoppingListProviderRef ref) {
  print('[shoppingListProvider] Fetching shopping list...');
  final shoppingRepo = ref.watch(shoppingRepositoryProvider);
  return shoppingRepo.watchShoppingItems().map((items) {
    print('[shoppingListProvider] ✅ Received ${items.length} shopping items');
    return items;
  });
}

/// FutureProvider for adding a single meal.
@riverpod
Future<void> addMeal(
  AddMealRef ref, {
  required String recipeName,
  required DateTime mealDate,
  required String mealType,
  String? notes,
  String? prepGroupId,
}) async {
  print('[addMeal] Called for recipeName: $recipeName');
  try {
    final mealRepo = ref.watch(mealPlanRepositoryProvider);
    await mealRepo.addMeal(
      recipeName: recipeName,
      mealDate: mealDate,
      mealType: mealType,
      notes: notes,
      prepGroupId: prepGroupId,
    );

    // Refresh meals
    ref.invalidate(todayMealsProviderProvider);
    ref.invalidate(allMealsProviderProvider);

    print('[addMeal] ✅ Meal added');
  } catch (e) {
    print('[addMeal] ❌ Error: $e');
    rethrow;
  }
}

/// FutureProvider for bulk inserting a 3-day meal prep.
@riverpod
Future<String> bulkInsertMealPrep(
  BulkInsertMealPrepRef ref, {
  required List<Map<String, dynamic>> meals,
  String? autoGeneratedPrepGroupId,
}) async {
  print('[bulkInsertMealPrep] Called with ${meals.length} meals');
  try {
    final mealRepo = ref.watch(mealPlanRepositoryProvider);
    final shoppingRepo = ref.watch(shoppingRepositoryProvider);

    final prepGroupId = await mealRepo.bulkInsertMealPrep(
      meals: meals,
      autoGeneratedPrepGroupId: autoGeneratedPrepGroupId,
    );

    // Automatically generate shopping list from the meal prep
    // Use ingredientsList if available, fallback to recipe names
    final shoppingItems = <Map<String, dynamic>>[];
    final seenIngredients = <String>{};

    for (final meal in meals) {
      final ingredientsList =
          meal['ingredientsList'] as List<Map<String, dynamic>>?;
      final recipeName = meal['recipeName'] as String;

      if (ingredientsList != null && ingredientsList.isNotEmpty) {
        // Format each ingredient as "[Amount] [Unit] [Name]"
        for (final ingredient in ingredientsList) {
          final name = ingredient['name'] as String? ?? '';
          final amount = ingredient['amount'] as String?;
          final unit = ingredient['unit'] as String?;

          if (name.isNotEmpty) {
            // Build formatted ingredient string
            final parts = <String>[];
            if (amount != null && amount.isNotEmpty) parts.add(amount);
            if (unit != null && unit.isNotEmpty) parts.add(unit);
            parts.add(name);
            final formatted = parts.join(' ');

            if (!seenIngredients.contains(formatted)) {
              seenIngredients.add(formatted);
              shoppingItems.add({
                'title': formatted,
                'linkedPrepGroupId': prepGroupId,
              });
            }
          }
        }
      } else {
        // Fallback to recipe name if no ingredients
        if (!seenIngredients.contains(recipeName)) {
          seenIngredients.add(recipeName);
          shoppingItems.add({
            'title': recipeName,
            'linkedPrepGroupId': prepGroupId,
          });
        }
      }
    }

    if (shoppingItems.isNotEmpty) {
      await shoppingRepo.bulkAddShoppingItems(shoppingItems);
      print(
        '[bulkInsertMealPrep] ✅ Generated ${shoppingItems.length} shopping items',
      );
    }

    // Refresh meals and shopping list
    ref.invalidate(todayMealsProviderProvider);
    ref.invalidate(allMealsProviderProvider);
    ref.invalidate(shoppingListProviderProvider);

    print(
      '[bulkInsertMealPrep] ✅ Bulk meal prep inserted with prepGroupId: $prepGroupId',
    );
    return prepGroupId;
  } catch (e) {
    print('[bulkInsertMealPrep] ❌ Error: $e');
    rethrow;
  }
}

/// FutureProvider for updating a meal.
@riverpod
Future<void> updateMeal(UpdateMealRef ref, MealPlan meal) async {
  print('[updateMeal] Called for mealId: ${meal.id}');
  try {
    final mealRepo = ref.watch(mealPlanRepositoryProvider);
    await mealRepo.updateMeal(meal);

    // Refresh meals
    ref.invalidate(todayMealsProviderProvider);
    ref.invalidate(allMealsProviderProvider);

    print('[updateMeal] ✅ Meal updated successfully');
  } catch (e) {
    print('[updateMeal] ❌ Error: $e');
    rethrow;
  }
}

/// FutureProvider for deleting a meal.
@riverpod
Future<void> deleteMeal(DeleteMealRef ref, String mealId) async {
  print('[deleteMeal] Called for mealId: $mealId');
  try {
    final mealRepo = ref.watch(mealPlanRepositoryProvider);
    await mealRepo.deleteMeal(mealId);

    // Refresh meals
    ref.invalidate(todayMealsProviderProvider);
    ref.invalidate(allMealsProviderProvider);

    print('[deleteMeal] ✅ Meal deleted successfully');
  } catch (e) {
    print('[deleteMeal] ❌ Error: $e');
    rethrow;
  }
}

/// FutureProvider for updating a shopping item (e.g., toggle bought status).
@riverpod
Future<void> updateShoppingItem(
  UpdateShoppingItemRef ref,
  ShoppingItem item,
) async {
  print('[updateShoppingItem] Called for itemId: ${item.id}');
  try {
    final shoppingRepo = ref.watch(shoppingRepositoryProvider);
    await shoppingRepo.updateShoppingItem(item);

    // Refresh shopping list
    ref.invalidate(shoppingListProviderProvider);

    print('[updateShoppingItem] ✅ Shopping item updated successfully');
  } catch (e) {
    print('[updateShoppingItem] ❌ Error: $e');
    rethrow;
  }
}

/// FutureProvider for deleting a shopping item.
@riverpod
Future<void> deleteShoppingItem(
  DeleteShoppingItemRef ref,
  String itemId,
) async {
  print('[deleteShoppingItem] Called for itemId: $itemId');
  try {
    final shoppingRepo = ref.watch(shoppingRepositoryProvider);
    await shoppingRepo.deleteShoppingItem(itemId);

    // Refresh shopping list
    ref.invalidate(shoppingListProviderProvider);

    print('[deleteShoppingItem] ✅ Shopping item deleted successfully');
  } catch (e) {
    print('[deleteShoppingItem] ❌ Error: $e');
    rethrow;
  }
}

/// CombinedProvider for shopping cycles (grouped by prep_group_id).
@riverpod
Stream<List<ShoppingCycle>> shoppingCyclesProvider(
  ShoppingCyclesProviderRef ref,
) {
  print('[shoppingCyclesProvider] Fetching shopping cycles...');
  final shoppingRepo = ref.watch(shoppingRepositoryProvider);
  final mealRepo = ref.watch(mealPlanRepositoryProvider);

  // Combine both streams
  return shoppingRepo.watchShoppingItems().asyncExpand((shoppingItems) {
    return mealRepo.watchAllMeals().map((allMeals) {
      print(
        '[shoppingCyclesProvider] Processing ${shoppingItems.length} items and ${allMeals.length} meals',
      );

      // Group shopping items by prepGroupId
      final cycles = <String?, List<ShoppingItem>>{};

      for (final item in shoppingItems) {
        final groupId = item.linkedPrepGroupId ?? 'manual';
        cycles.putIfAbsent(groupId, () => []).add(item);
      }

      // Convert groups to ShoppingCycle objects with date ranges
      final shoppingCycles = <ShoppingCycle>[];

      for (final entry in cycles.entries) {
        final groupId = entry.key;
        final items = entry.value;

        if (groupId == 'manual') {
          // Manual items - no associated prep group
          shoppingCycles.add(
            ShoppingCycle(
              prepGroupId: null,
              startDate: DateTime.now(),
              endDate: DateTime.now(),
              mealPrepSetName: 'Ręcznie dodane',
              items: items,
            ),
          );
        } else {
          // Find associated meals to get the date range
          final associatedMeals = allMeals
              .where((meal) => meal.prepGroupId == groupId)
              .toList();

          if (associatedMeals.isNotEmpty) {
            associatedMeals.sort((a, b) => a.mealDate.compareTo(b.mealDate));
            final startDate = associatedMeals.first.mealDate;
            final endDate = associatedMeals.last.mealDate;

            shoppingCycles.add(
              ShoppingCycle(
                prepGroupId: groupId,
                startDate: startDate,
                endDate: endDate,
                items: items,
              ),
            );
          }
        }
      }

      // Sort cycles by start date
      shoppingCycles.sort((a, b) => a.startDate.compareTo(b.startDate));

      print(
        '[shoppingCyclesProvider] ✅ Created ${shoppingCycles.length} cycles',
      );
      return shoppingCycles;
    });
  });
}

/// StateProvider to track the selected shopping cycle index.
@riverpod
class SelectedCycleIndex extends _$SelectedCycleIndex {
  @override
  int build() => 0;

  void select(int index) => state = index;

  void next() => state++;

  void previous() {
    if (state > 0) state--;
  }
}

/// FutureProvider for manually adding a shopping item.
@riverpod
Future<void> addShoppingItem(
  AddShoppingItemRef ref, {
  required String title,
  String? linkedPrepGroupId,
}) async {
  print('[addShoppingItem] Called with title: $title');
  try {
    final shoppingRepo = ref.watch(shoppingRepositoryProvider);
    await shoppingRepo.addShoppingItem(
      title: title,
      linkedPrepGroupId: linkedPrepGroupId,
    );

    // Refresh shopping cycles
    ref.invalidate(shoppingCyclesProviderProvider);
    ref.invalidate(shoppingListProviderProvider);

    print('[addShoppingItem] ✅ Shopping item added successfully');
  } catch (e) {
    print('[addShoppingItem] ❌ Error: $e');
    rethrow;
  }
}
