import '../domain/meal_plan.dart';

/// Abstract interface for meal plan operations.
abstract class MealPlanRepository {
  /// Watch meals for a specific date.
  /// Filters by meal_date and current user's household_id.
  Stream<List<MealPlan>> watchMealsForDate(DateTime date);

  /// Watch all meals in a household (can be used for calendar view).
  Stream<List<MealPlan>> watchAllMeals();

  /// Add a single meal to the plan.
  Future<void> addMeal({
    required String recipeName,
    required DateTime mealDate,
    required String mealType,
    String? ingredients,
    String? instructions,
    List<Map<String, dynamic>>? ingredientsList,
    List<Map<String, dynamic>>? instructionsList,
    String? notes,
    String? prepGroupId,
  });

  /// Bulk insert multiple meals from a 3-day prep wizard.
  /// Returns the generated prep_group_id.
  Future<String> bulkInsertMealPrep({
    required List<Map<String, dynamic>> meals,
    String? autoGeneratedPrepGroupId,
  });

  /// Update an existing meal.
  Future<void> updateMeal(MealPlan meal);

  /// Delete a meal by ID.
  Future<void> deleteMeal(String mealId);

  /// Get meals by prep_group_id (e.g., for shopping list generation).
  Future<List<MealPlan>> getMealsByPrepGroupId(String prepGroupId);
}
