import 'package:uuid/uuid.dart';
import 'package:supabase_flutter/supabase_flutter.dart' as supabase;

import '../domain/meal_plan.dart';
import 'meal_plan_repository.dart';

/// Concrete implementation of MealPlanRepository using Supabase.
class MealPlanRepositoryImpl implements MealPlanRepository {
  final supabase.SupabaseClient _supabase;
  final String Function() getHouseholdId;

  MealPlanRepositoryImpl(this._supabase, {required this.getHouseholdId});

  @override
  Stream<List<MealPlan>> watchMealsForDate(DateTime date) {
    final userId = _supabase.auth.currentUser?.id;
    final householdId = getHouseholdId();

    final dateStr = date.toIso8601String().split('T')[0]; // Format: YYYY-MM-DD
    print(
      '[watchMealsForDate] Fetching meals for date: $dateStr, householdId: $householdId',
    );

    if (userId == null || householdId.isEmpty) {
      print(
        '[watchMealsForDate] ❌ Missing user ID or household ID - returning empty stream',
      );
      return Stream.value([]);
    }

    return _supabase
        .from('meal_plan')
        .stream(primaryKey: ['id'])
        .eq('household_id', householdId)
        .map((data) {
          print(
            '[watchMealsForDate] Raw data received: ${data.length} records',
          );
          final meals = (data as List<dynamic>)
              .where((json) {
                final mealDate = json['meal_date'] as String;
                final matches = mealDate == dateStr;
                return matches;
              })
              .map((json) => _mealFromJson(json as Map<String, dynamic>))
              .toList();
          print(
            '[watchMealsForDate] ✅ Received ${meals.length} meals for date: $dateStr',
          );
          return meals;
        });
  }

  @override
  Stream<List<MealPlan>> watchAllMeals() {
    final userId = _supabase.auth.currentUser?.id;
    final householdId = getHouseholdId();

    print('[watchAllMeals] Fetching all meals, householdId: $householdId');

    if (userId == null || householdId.isEmpty) {
      print(
        '[watchAllMeals] ❌ Missing user ID or household ID - returning empty stream',
      );
      return Stream.value([]);
    }

    return _supabase
        .from('meal_plan')
        .stream(primaryKey: ['id'])
        .eq('household_id', householdId)
        .order('meal_date')
        .map((data) {
          print('[watchAllMeals] Raw data received: ${data.length} records');
          final meals = (data as List<dynamic>)
              .map((json) => _mealFromJson(json as Map<String, dynamic>))
              .toList();
          print('[watchAllMeals] ✅ Received ${meals.length} meals');
          return meals;
        });
  }

  @override
  Future<void> addMeal({
    required String recipeName,
    required DateTime mealDate,
    required String mealType,
    String? ingredients,
    String? instructions,
    List<Map<String, dynamic>>? ingredientsList,
    List<Map<String, dynamic>>? instructionsList,
    String? notes,
    String? prepGroupId,
  }) async {
    print(
      '[addMeal] Adding meal: recipeName=$recipeName, mealDate=$mealDate, mealType=$mealType',
    );
    try {
      final userId = _supabase.auth.currentUser?.id;
      final householdId = getHouseholdId();

      if (userId == null || householdId.isEmpty) {
        print('[addMeal] ❌ User not authenticated or not in a household');
        throw Exception('User must be authenticated and in a household');
      }

      final mealDateStr = mealDate.toIso8601String().split(
        'T',
      )[0]; // Format: YYYY-MM-DD

      await _supabase.from('meal_plan').insert({
        'recipe_name': recipeName,
        'meal_date': mealDateStr,
        'meal_type': mealType,
        'ingredients': ingredients,
        'instructions': instructions,
        'ingredients_list': ingredientsList,
        'instructions_list': instructionsList,
        'notes': notes,
        'owner_id': userId,
        'household_id': householdId,
        'prep_group_id': prepGroupId,
        'is_meal_prep': false,
        'is_household': true,
      });

      print('[addMeal] ✅ Meal added successfully');
    } catch (e) {
      print('[addMeal] ❌ Error adding meal: $e');
      rethrow;
    }
  }

  @override
  Future<String> bulkInsertMealPrep({
    required List<Map<String, dynamic>> meals,
    String? autoGeneratedPrepGroupId,
  }) async {
    print('[bulkInsertMealPrep] Inserting ${meals.length} meals');
    try {
      final userId = _supabase.auth.currentUser?.id;
      final householdId = getHouseholdId();

      if (userId == null || householdId.isEmpty) {
        print(
          '[bulkInsertMealPrep] ❌ User not authenticated or not in a household',
        );
        throw Exception('User must be authenticated and in a household');
      }

      // Generate a UUID for the prep session if not provided
      final prepGroupId = autoGeneratedPrepGroupId ?? const Uuid().v4();

      // Enrich meals with user data and prep group id
      final enrichedMeals = meals.map((meal) {
        final mealDate = meal['mealDate'] as DateTime;
        final mealDateStr = mealDate.toIso8601String().split('T')[0];

        return {
          'recipe_name': meal['recipeName'],
          'meal_date': mealDateStr,
          'meal_type': meal['mealType'],
          'ingredients': meal['ingredients'],
          'instructions': meal['instructions'],
          'ingredients_list': meal['ingredientsList'],
          'instructions_list': meal['instructionsList'],
          'notes': meal['notes'],
          'owner_id': userId,
          'household_id': householdId,
          'prep_group_id': prepGroupId,
          'is_meal_prep': true,
          'is_household': true,
        };
      }).toList();

      await _supabase.from('meal_plan').insert(enrichedMeals);

      print(
        '[bulkInsertMealPrep] ✅ Inserted ${meals.length} meals with prep_group_id: $prepGroupId',
      );

      return prepGroupId;
    } catch (e) {
      print('[bulkInsertMealPrep] ❌ Error bulk inserting meals: $e');
      rethrow;
    }
  }

  @override
  Future<void> updateMeal(MealPlan meal) async {
    print('[updateMeal] Updating meal: ${meal.id}');
    try {
      final mealDateStr = meal.mealDate.toIso8601String().split('T')[0];

      await _supabase
          .from('meal_plan')
          .update({
            'recipe_name': meal.recipeName,
            'meal_date': mealDateStr,
            'meal_type': meal.mealType,
            'ingredients': meal.ingredients,
            'instructions': meal.instructions,
            'ingredients_list': meal.ingredientsList
                .map((ing) => ing.toJson())
                .toList(),
            'instructions_list': meal.instructionsList
                .map((instr) => instr.toJson())
                .toList(),
            'notes': meal.notes,
            'is_household': meal.isHousehold,
          })
          .eq('id', meal.id);

      print('[updateMeal] ✅ Meal updated successfully');
    } catch (e) {
      print('[updateMeal] ❌ Error updating meal: $e');
      rethrow;
    }
  }

  @override
  Future<void> deleteMeal(String mealId) async {
    print('[deleteMeal] Deleting meal: $mealId');
    try {
      await _supabase.from('meal_plan').delete().eq('id', mealId);

      print('[deleteMeal] ✅ Meal deleted successfully');
    } catch (e) {
      print('[deleteMeal] ❌ Error deleting meal: $e');
      rethrow;
    }
  }

  @override
  Future<List<MealPlan>> getMealsByPrepGroupId(String prepGroupId) async {
    print(
      '[getMealsByPrepGroupId] Fetching meals for prepGroupId: $prepGroupId',
    );
    try {
      final householdId = getHouseholdId();

      final response = await _supabase
          .from('meal_plan')
          .select()
          .eq('household_id', householdId)
          .eq('prep_group_id', prepGroupId);

      final meals = (response as List<dynamic>)
          .map((json) => _mealFromJson(json as Map<String, dynamic>))
          .toList();

      print(
        '[getMealsByPrepGroupId] ✅ Retrieved ${meals.length} meals for prepGroupId: $prepGroupId',
      );

      return meals;
    } catch (e) {
      print('[getMealsByPrepGroupId] ❌ Error fetching meals: $e');
      rethrow;
    }
  }

  /// Helper to convert JSON from Supabase to MealPlan domain model.
  MealPlan _mealFromJson(Map<String, dynamic> json) {
    // Parse ingredients list
    final ingredientsListJson = json['ingredients_list'] as List<dynamic>?;
    final ingredientsList = ingredientsListJson != null
        ? ingredientsListJson
              .map((item) => Ingredient.fromJson(item as Map<String, dynamic>))
              .toList()
        : <Ingredient>[];

    // Parse instructions list
    final instructionsListJson = json['instructions_list'] as List<dynamic>?;
    final instructionsList = instructionsListJson != null
        ? instructionsListJson
              .map(
                (item) =>
                    InstructionStep.fromJson(item as Map<String, dynamic>),
              )
              .toList()
        : <InstructionStep>[];

    return MealPlan(
      id: json['id'] as String,
      householdId: json['household_id'] as String,
      ownerId: json['owner_id'] as String,
      recipeName: json['recipe_name'] as String,
      mealDate: DateTime.parse(json['meal_date'] as String),
      mealType: json['meal_type'] as String,
      ingredients: json['ingredients'] as String?,
      instructions: json['instructions'] as String?,
      ingredientsList: ingredientsList,
      instructionsList: instructionsList,
      notes: json['notes'] as String?,
      prepGroupId: json['prep_group_id'] as String?,
      isMealPrep: json['is_meal_prep'] as bool? ?? false,
      isHousehold: json['is_household'] as bool? ?? true,
      createdAt: DateTime.parse(
        json['created_at'] as String? ?? DateTime.now().toIso8601String(),
      ),
    );
  }
}
